import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "./compoments/Navbar";
import Bootstrapclient from "./compoments/Bootstrapclient";
import 'bootstrap-icons/font/bootstrap-icons.min.css';
import Footer from "./compoments/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
      <Bootstrapclient />

    </html>
  );
}
